---
box: jayunit100/centos7
ip: "192.168.44.45"
memory: 2048
cpus: 1
provider: virtualbox
folders:
    - map: ~/allproject
      to: /home/vagrant/JH
    - map: ~/allproject/datamysql/mysql01
      to: /var/lib/mysql01
    - map: ~/allproject/datamysql/mysql02
      to: /var/lib/mysql02
sites:
    - map: superstar.dev
      to: /home/vagrant/JH/superstar/public
    - map: hawaiioption.dev
      to: /home/vagrant/JH/hawaiioption/public
    - map: api.dev
      to: /home/vagrant/JH/api/public
variables:
    - key: APP_ENV
      value: local

# ports:
#     - send: 93000
#       to: 9300
#     - send: 7777
#       to: 777
#       protocol: udp
